### ISSUE TITLE
How to use aliases in the tests?

### ISSUE THREAD

**Issue by hemulin** [wesssel/nuxt-unit-testing#1]
In the List.js test ([here](https://github.com/wesssel/nuxt-unit-testing/blob/f5f7cba8d87b82e7219c92fd2fb77f63c655d00f/test/specs/List.js#L3)) you're calling the component by its relative path.

1. How can one use aliases (`@`) to access the to-be-mounted component?
2. How could I test multi-level components? Currently the test fails (because the nested component is being imported with an alias `@` which is probably related to (1), but worth checking).

Thanks for this repo, it is very helpful.

**Comment by wesssel** [comment]
I tried to find a solution for the aliases but does not work with https://github.com/jackmellis/require-extension-hooks

I am trying to setup Nuxt + Jest + Webpack to resolve these paths.

If anyone has an idea how to fix, please create a PR or write here

**Comment by hemulin** [comment]
@wesssel Haven't used it yet but I plan soon to try it out:

https://github.com/studbits/nuxt-jest-puppeteer

**Comment by wesssel** [comment]
@hemulin,

Great thanks. Hope Nuxt comes with unit tests themselves at some point...

**Comment by Norbz** [comment]
I used this module :
https://github.com/tleunen/babel-plugin-module-resolver

And specifying the aliases in packages.json
```
"babel": {
    "presets": [
     /* ... */
    ],
    "plugins": [
      [
        "module-resolver",
        {
          "root": [
            "./src"
          ],
          "alias": {
            "@": "./src",
            "~": "./src"
          }
        }
      ]
    ]
  }
```

My code is within a src folder, but you could just point it to `./` in default folder structure

**Comment by wesssel** [comment]
@Norbz,

Thank you for the solution. I added this to the repo
