### ISSUE TITLE
error Command "ava" not found.

### ISSUE THREAD

**Issue by wushan** [wesssel/nuxt-unit-testing#3]
I cloned this project and followed the instruction step by step.

when I run `yarn test:unit`, always get `error Command "ava" not found.` error. Am I doing anything wrong or this repo has broken ?

**Comment by wesssel** [comment]
@wushan what are your `yarn` and `node` versions? Mine are yarn: `1.9.x` Node: `8.x.x`

**Comment by wesssel** [comment]
Should work with given `yarn` and `node` version
